### ISSUE TITLE
It seems to download something rather different than what I see.

### ISSUE THREAD

**Issue by mzso** [darxmorph/VideoDownloader#1]
Hi!
I tried this [url](https://www.formula1.com/en/latest/article.watch-sainz-and-norriss-views-of-lap-1-tangle-with-kvyat.2yqDqRIVxj0vk7Na89Gzdv.html). And while the downloaded file shows the same incident the order of the on-board views is different. Also playing online, radio messages are also added to the video, and the video's longer. 

Very strange.

**Comment by darxmorph** [comment]
Hi,
Could you please provide the URL that causes this issue so that I can take a look at it?

Thanks.

**Comment by mzso** [comment]
Hmmm it looks like the URL somehow got lost: https://www.formula1.com/en/latest/article.watch-sainz-and-norriss-views-of-lap-1-tangle-with-kvyat.2yqDqRIVxj0vk7Na89Gzdv.html

It still happens.

**Comment by darxmorph** [comment]
It looks like, for some bizarre reason, the HDS stream is pointing to a different video than the rest.

I haven't seen this kind of behavior with any other videos, but I'm considering adding an option to download an .mp4 instead.

In the meantime, you should be able to download the video from [here](https://f1.pc.cdn.bitgravity.com/1wbmptaDE6g5PthTxZhKDyUQTrqQB-mS/DOcJ-FxaFrRg4gtDMwOjQ0YzowczE7OJ).

**Comment by mzso** [comment]
[**@darxmorph**](https://github.com/darxmorph) commented on [2019. ápr. 19. 00:38 CEST](https://github.com/darxmorph/VideoDownloader/issues/1#issuecomment-484712507 "2019-04-18T22:38:07Z - Replied by Github Reply Comments"):
> It looks like, for some bizarre reason, the HDS stream is pointing to a different video than the rest.
> 
> I haven't seen this kind of behavior with any other videos, but I'm considering adding an option to download an .mp4 instead.
> 
> In the meantime, you should be able to download the video from [here](https://f1.pc.cdn.bitgravity.com/1wbmptaDE6g5PthTxZhKDyUQTrqQB-mS/DOcJ-FxaFrRg4gtDMwOjQ0YzowczE7OJ).

Cool. There's a separate mp4 stream provided? How come you chose the FLV stream for the downloader?

**Comment by darxmorph** [comment]
I'm not really sure why I did, but the new release I've just posted downloads the mp4 stream by default.

Hopefully this should solve your issue :)

**Comment by mzso** [comment]
[**@darxmorph**](https://github.com/darxmorph) commented on [2019. máj. 1. 18:40 CEST](https://github.com/darxmorph/VideoDownloader/issues/1#issuecomment-488336357 "2019-05-01T16:40:03Z - Replied by Github Reply Comments"):
> I'm not really sure why I did, but the new release I've just posted downloads the mp4 stream by default.
> 
> Hopefully this should solve your issue :)

Great. Thanks.
