### ISSUE TITLE
App crashes when download is started.

### ISSUE THREAD

**Issue by Bart-NL** [darxmorph/VideoDownloader#2]
Whatever formula1.com-url I use, everytime I click 'Download' the app crashes.
It doesn't matter if I select 'prefer MP4' or not. I get some sort of 'connection closed' error.

Running the application as Administrator makes no difference.

Since I'm using a Dutch version of Windows 10 the error I get is in Dutch so probably doesn't help much. Should the most recent version work with the current Formula1.com website-video's?

**Comment by darxmorph** [comment]
Hi,

Apparently the issue was that their servers started rejecting TLSv1.0 (which is good from a security perspective), however the .NET Framework version I'm using only negotiates up to TLSv1.0 by default. The new version should work fine for you.

Thank you for reporting the issue, and stay safe!
