### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by leocecchet** [darxmorph/VideoDownloader#3]
Hello, try get video from new links:

https://www.formula1.com/en/latest/article.must-see-bottas-and-norris-end-up-down-same-escape-road-in-first-practice-in.5cfSMDM3q6fQC7WZKZ9G6U.html

https://www.formula1.com/en/latest/article.watch-leclerc-wipes-off-his-front-wing-on-baku-barriers-in-practice-shunt.o92N4LIXRgEKIvYfeL4MD.html

**Comment by darxmorph** [comment]
Thanks for letting me know, it should be fixed now.
